config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
    root to: "public/homes#top"
    
namespace :admin do
    resources :items,only: [:index,:new,:create,:show,:edit,:update]
    
    resources :customers
    
    resources :orders,only: [:index,:show,:update]
    
    
  end

namespace :public do
   
   
    get '/about' => 'homes#about'
    
    resources :customers,only: [:update] do
        collection do
         get 'customers/mypage' => 'customers#show'
         get 'customers/information/edit' => 'customers#edit'
         patch '/customers' => 'customers#update', as: 'update_customer'
         get 'confirm_withdraw'
         patch 'withdraw'
        end
      end
    
    resources :items,only: [:index,:show]
    
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items,only: [:index,:update,:create,:destroy]
    
    resources :orders,only: [:new,:index,:show,:create] do
       collection do
          post 'confirm'
          get 'complete'
        end
      end
  end
  
 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    
    enum payment_method: { credit_card: 0, transfer: 1 }
    
    belongs_to :customer
	has_many :order_details, dependent: :destroy
    has_many :items, through: :order_details
	
	validates :customer_id, :address, :receiver, :postage, :total_price, :payment_method, presence: true
	
	validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
	validates :postage, :total_price, numericality: { only_integer: true }

    
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    
     before_action :authenticate_admin!
    
     def index
  	  @orders = Order.all.page(params[:page]).per(10)
	end
    
     def show
       @order = Order.find(params[:id])
       @order_details = @order.order_details
     end
     
     

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<h2>注文履歴一覧</h2>

 <table class="table table-hover table-bordered table-condensed">
		  <thead>
		    <tr>
		      <th>購入日時</th>
	      	  <th>購入者</th>
		      <th>注文個数</th>
		    </tr>
		  </thead>
		  
		  <tbody>
		    <% @orders.each do |order| %>
		  　 <tr>
		        <td>
		        <%= link_to admin_order_path(order) do %><%= order.created_at.strftime('%Y/%m/%d%T') %><% end %>
		        </td>
		        <td><%= order.receiver %></td>
		        <td><%= order.order_details.sum(:amount) %></td>
    	        <td></td>
     	      </tr>
		    <% end %>
		  </tbody>
		</table>
		
		 
		<%= paginate(@orders) %>

app/views/admin/orders/show.html.erb
<div class="container">
<h3>注文履歴詳細</h3>
<table>
<tr>
	<td>購入者</td><td><%= @order.receiver %></td>
</tr>
<tr>
    <td>注文日</td><td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
</tr>
<tr> 
    <td>配送先</td><td><%= @order.address%></td>
</tr>
<tr>
    <td>支払い方法</td><td><%= @order.payment_method_i18n %></td>
</tr>
</table>

 <div class="row">
 	 <div class="col-xs-6">
 <table class="table table-hover table-bordered table-condensed">
		<thead>
			<tr>
			   <th>商品名</th>
			   <th>単価（税込）</th>
			   <th>数量</th>
			   <th>小計</th>
			</tr>
		</thead>
		
		<tbody>
		<% @order_details.each do |order_detail| %>
					<tr>
			            <td>
			              <%= order_detail.item.name %>
			            </td>
			            <td>
			              <%= (order_detail.price * 1.1).floor.to_s(:delimited) %>
			            </td>
			            <td>
			              <%= order_detail.amount %>
			            </td>
			            <td>
			              <%= (order_detail.price * order_detail.amount * 1.1).floor.to_s(:delimited) %>
			            </td>
			        </tr>
				<% end %>
		</tbody>
</table>
</div>
</div>


<div class="col-xs-6">
       <table class="table table-hover table-inverse table-bordered">
            <tr>
              <th>商品合計</th>
              <td><%= (@order.total_price - @order.postage).to_s(:delimited) %></td>
            </tr>
            <tr>
              <th>送料</th>
              <td><%= @order.postage.to_s(:delimited) %></td>
            </tr>
            <tr>
              <th>請求金額合計</th>
              <td><%= @order.total_price.to_s(:delimited) %></td>
            </tr>
        </table>
  </div>