config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
    root to: "public/homes#top"
    
namespace :admin do
    resources :items,only: [:index,:new,:create,:show,:edit,:update]
    
    resources :customers
    
    resources :orders,only: [:index,:show,:update]
    
    
  end

namespace :public do
   
   
    get '/about' => 'homes#about'
    
    resources :customers,only: [:update] do
        collection do
         get 'customers/mypage' => 'customers#show'
         get 'customers/information/edit' => 'customers#edit'
         patch '/customers' => 'customers#update', as: 'update_customer'
         get 'confirm_withdraw'
         patch 'withdraw'
        end
      end
    
    resources :items,only: [:index,:show]
    
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items,only: [:index,:update,:create,:destroy]
    
    resources :orders,only: [:new,:index,:show,:create] do
       collection do
          post 'confirm'
          get 'complete'
        end
      end
  end
  
 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
 <header>
   <div class="container">
    
    <div class="row">
      <nav class="nav navbar-nav navbar-left">
        <%= link_to "LOGO", root_path %>
      </nav>
    </div>
      
  
    
     <nav class="nav-item nav navbar-nav navbar-right">
    
    <% if customer_signed_in? %>
     
            ようこそ、<%= current_customer.last_name %>さん！
          <!--ユーザーがログインしている時 -->
          <li><%= link_to "マイページ", customers_mypage_public_customers_path %></li>
          <li><%= link_to "商品一覧", public_items_path %></li>
          <li><%= link_to "カート", public_cart_items_path %></li>
          <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete %></li>
    
    <% elsif admin_signed_in? %>
           <!--管理者がログインしている時 -->
          <li><%= link_to "商品一覧", admin_items_path %></li>
          <li><%= link_to "会員一覧", admin_customers_path %></li>
          <li><%= link_to "注文履歴一覧", admin_orders_path %></li>
          <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
            
    <% else %>
           <!--ログインしていない時　-->
            <li><%= link_to "About", public_about_path %></li>
            <li><%= link_to "商品一覧", public_items_path %> </li>
            <li><%= link_to "新規登録", new_customer_registration_path %></li>
            <li><%= link_to "ログイン", new_customer_session_path %></li>
    <% end %>
     
     
    </nav>
  </div>
 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
   
    <%= yield %>
  </body>
</html>